version: '3.8'

services:
  # Serviço da aplicação Java
  hubspot-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hubspot_api
    environment:
      - AMBIENTE=prod
    ports:
      - "8080:8080"
